package com.example.rutescompartidesapp.view.faq.components

val faqItems = listOf(
    FaqItemModel("Isoterm", "Transport amb vehicle amb parets aïllants, manté la temperatura", "Cercant Rutes/Comandes"),
    FaqItemModel("Refrigerat", "Transport amb vehicle amb font de fred, temperatures de 4 a 12º (cal confirmar temperatura exacta amb qui ofereix el transport)", "Cercant Rutes/Comandes"),
    FaqItemModel("Congelat", "Transport amb vehicle amb font de fred, temperatures inferiors a 0º (cal confirmar temperatura exacta amb qui ofereix el transport).", "Cercant Rutes/Comandes"),
    FaqItemModel("Sense humitat", "Rutes en les quals no es transporten verdures o altres productes que produeixin humitat (vehicle compatible per al transport de pa, llavors, pasta, etc.).", "Cercant Rutes/Comandes"),
    FaqItemModel("Etiquetes", "Les etiquetes permeten categoritzar les rutes/comandes i així poder-les cercar específicament.", "Cercant Rutes/Comandes"),
    FaqItemModel("'Desv. Orige: X,X km' i 'Desv. Destinacio: X,X km'", "Aquesta informació indica la distància en km que la necessitat indicada en el cercador fa desviar la ruta del seu camí. El cercador només troba la ruta si aquestes distàncies són inferiors a la desviació màxima que s'ha indicat al crear la ruta.", "Cercant Rutes/Comandes"),
    FaqItemModel("Nom intern de la ruta", "Nom per tal que l'usuari sàpiga a quina ruta fa referència. Per exemple, si cada setmana fa la ruta Lleida-Tarragona, i està creant la ruta del 10 de gener, podria ser LLDA-TGN-10G, i així en un cop d'ull es diferencia de LLDA-TGN-3G, LLDA-TGN-17G, etc.", "Creant una ruta"),
    FaqItemModel("Punt intermig", "Punt pel qual passa la ruta (per què l'aplicació esculli la carretera correcta o per indicar que la ruta hi fa parada).", "Creant una ruta"),
    FaqItemModel("Maxim desviament de la ruta", "Quilòmetres que la persona que fa la ruta està diposada a desviar-se d'aquesta en qualsevol punt de la ruta. Per defecte són 10km. Aquest camp és molt important perquè el cercador trobarà o no la ruta en funció d'això, i no té sentit rebre comandes a distàncies que qui fa la ruta no està diposat/da a assumir.", "Creant una ruta"),
    FaqItemModel("Seients disponibles per compartir", "Opció d'oferir seients disponibles sense especificar en quin/s tram/s del trajecte. És una funcionalitat secundària i una característica per la qual no es pot filtrar a l'hora de fer cerques.", "Creant una ruta"),
    FaqItemModel("Espai disponible al vehicle", "Espai en metres cúbics que el vehicle que fa la ruta té disponible. És una xifra orientativa, que no s'actualitza a la que la ruta va acceptant comandes.", "Creant una ruta"),
    FaqItemModel("Cost en € per cada KM recorregut", "L'app no integra el pagament. Qui crea la ruta indica quants euros per Km podria costar posar-hi un paquet. Però cal sempre especificar a quin acord s'arriba en entrar en contacte amb l'altra part, ja que el pes o el volum de la comanda pot fer-ne variar els costos.", "Creant una ruta"),
    FaqItemModel("Model de vehicle/furgoneta", "Per transmetre a les possibles comandes les possibilitats de transport (no és el mateix una Berlingo que un camió). Indicar el color, pot ajudar a trobar-se més fàcilment.", "Creant una ruta"),
    FaqItemModel("Nom intern de la comanda", "Nom per tal que l'usuari sàpiga a quina comanda fa referència. Per exemple, posant el nom del client/destinatari o el número de comanda/albarà del seu sistema de gestió.","Creant una comanda"),
    FaqItemModel("Data mínima d'arribada", "Data a partir de la qual tindràs el paquet a punt i pot ser transportat fins al seu destí","Creant una comanda"),
    FaqItemModel("Data màxima d'arribada", "Data i hora límit per entregar la comanda. Perquè la necessiten al destí (perquè tanquen més tard, o perquè ho necessiten per aquell dia com a màxim) o perquè és la data límit per decidir fer la ruta tu mateix/a si ningú assumeix la comanda.","Creant una comanda"),
    FaqItemModel("Data d'arribada flexible", "Si no tens pressa per entregar el paquet, aquesta opció fa que la comanda aparegui visible durant 1 mes. Passat aquest temps, si la comanda no ha trobat ruta, s'elimina automàticament per evitar acumular comandes que ja no necessiten ser transportades.","Creant una comanda"),
    FaqItemModel("Vull ocupar un seient buit al vehicle", "Opció d'aprofitar seients disponibles al vehicle de qui fa la ruta. És una funcionalitat secundària i una característica per la qual no es pot filtrar a l'hora de fer cerques.","Creant una comanda"),
    FaqItemModel("Nombres de paquets", "Indica quants paquets diferents inclou la teva comanda. Així qui fa la ruta tindrà clar quants paquets ha d'entregar en destí.","Creant una comanda"),
    FaqItemModel("Són fràgils", "Per productes/paquets que es trenquen amb facilitat. És un camp informatiu, perquè qui fa la ruta ho tingui present.","Creant una comanda"),
    FaqItemModel("Alçària, amplada, llargada i pes", "Si poses tots els paquets junts, quin espai ocupen? I quant pesen? Això és el que s'ha de posar en aquests camps.","Creant una comanda"),
    FaqItemModel("Rutes/Comandes actives", "Rutes/comandes amb data en el futur (o també data màxima flexible en el cas de les comandes).","Altres conceptes"),
    FaqItemModel("Rutes/Comandes antigues", "Rutes amb data del passat. Pot ser, però, que encara tinguin pendent accions de valoracions d'usuaris.","Altres conceptes"),
    FaqItemModel("Quin és el seu objectiu", "Que les pageses/elaboradores/artesanes puguin fer arribar les seves comandes de la forma més eficient possible: compartint les rutes. Així, es minimitzen els costos econòmics, els impactes mediambientals i el temps que cada persona ha de dedicar al transport.","Sobre aquesta app"),
    FaqItemModel("I quina és la seva funcionalitat principal?", "Que a l'estil de com es fa per compartir cotxe, qui ja fa rutes de distribució les pugui penjar i qui vol fer arribar una comanda trobi una ruta on sumar-se.","Sobre aquesta app"),
    FaqItemModel("Qui hi ha darrere d'aquest projecte", "Aquest és un projecte de Ponent Coopera, executat per Tres Cadires, la XEP i Komun, validat per un grup motor i un grup de contrast, i finançat per la Federació de Cooperatives de Treball de Catalunya i l'Einateca Agroecològica.","Sobre aquesta app"),
    FaqItemModel("És un projecte amb ànim de lucre?", "No. Ni les entitats ni els projectes abans mencionats tenen ànim de lucre, ni la pròpia app tampoc. De fet, és d'ús gratuït i desenvolupada amb programari lliure.","Sobre aquesta app"),
    FaqItemModel("Per què es crea aquesta app", "La idea de fer aquesta app era quelcom que ja hi havia persones de Ponent que tenien en ment, que llavors s'inclou en el projecte presentat a la Federació de Cooperatives de Treball de Catalunya per a resoldre necessitats de les productores agroecològiques de Ponent, i que finalment el procés de diagnosi del projecte valida i prioritza.","Sobre aquesta app"),
    FaqItemModel("És una app oberta a tothom? (a nivell d'us)", "Sí, és oberta a totes les pageses/elaboradores/artesanes que vulguin fer servir l’app. Tot i que inicialment està pensada per a ús de les productores agroecològiques, l'aplicació és oberta i disponible per a tothom. La qüestió és voler minimitzar la petjada ecològica de la distribució de mercaderies.","Sobre aquesta app"),
    FaqItemModel("És una app oberta a tothom? (a nivell de gestió)", "Sí. Més enllà de que tothom la pugui fer servir, tothom pot demanar participar del seu grup motor i decidir-ne els propers passos. Contacta'ns si és el teu cas.","Sobre aquesta app"),
    FaqItemModel("El seu ús està restringit a una zona o territori concret?", "No. Es podria fer servir a qualsevol lloc del món, ja que el mapa en què es basa és mundial. És un projecte que neix per resoldre necessitats de les productores de Ponent, i per tant s'ha fet molta feina perquè l'app sigui usada en aquest territori. Depèn de totes que també sigui molt usada en altres zones del país, fet que farà més fàcil poder compartir rutes més llargues.","Sobre aquesta app"),
    FaqItemModel("L'app assegura les mercaderies?", "No. Aquesta app no és un intermediari. Simplement facilita que les persones es trobin per tal de compartir rutes. No assegura de cap manera les mercaderies ni les persones que comparteixin ruta.","Sobre aquesta app"),
    FaqItemModel("L'app es fa responsable de l'ús que se'n pugui fer?", "Aquesta app ni els projectes que hi ha al darrere i l'han fet possible es fan responsables de l'ús que es faci d'aquesta app. L'app és una eina al servei del territori, res més.","Sobre aquesta app"),
    FaqItemModel("Quines són?", "Poder oferir rutes de distribució previstes per una banda (per qui té clar que farà aquella ruta però encara li queda espai al seu vehicle), i poder demanar rutes de distribució per l'altra (qui té clar que no pot fer ell/a mateixa la ruta i necessita algú que entomi la seva comanda).","Funcionalitats de l'app"),
    FaqItemModel("Què mostra l'app", "D'entrada, les cinc properes rutes i comandes. A partir d'aquí, pots cercar indicant punt de sortida, punt de destí o ambdues coses, i indicant a més a més la data i hora (mínima) si així ho requereixes.","Funcionalitats de l'app"),
    FaqItemModel("I si els meus productes requereixen d'un transport en fred o especial", "L'app permet crear rutes i filtrar per diversos tipus de transport (isotèrmic, refrigerat, congelat o sense humitat), de manera que qui busca transport pugui filtrar les rutes segons la necessitat dels seus productes. Quan algú se suma a una ruta (o crea la comanda a l'espera que aparegui algú que faci la ruta), llavors també pot indicar si la mercaderia és fràgil o qualsevol altre aspecte que consideri rellevant al camp de text de \"comentaris\".","Funcionalitats de l'app"),
    FaqItemModel("Puc comunicar-me amb altres usuaris (gent que fa o demanda rutes) a través de l'app?", "Sí. L'app facilita les dades de contacte de les dues parts, un cop acceptada la compartició d'una ruta; també hi ha la possibilitat d’entrar en contacte amb la persona que fa la ruta o que ofereix la comanda a través del xat intern (símbol de diàleg al costat del nom d’usuari).","Funcionalitats de l'app"),
    FaqItemModel("Com es compensa la feina de qui fa la ruta?", "L'app no entra en aquest aspecte, tot i que permet posar un cost per km quan es crea una ruta. En el moment que les dues parts accepten la ruta, llavors cal que es posin d'acord (fora de l'app) de tots els detalls, inclosa la manera de compensar el servei de qui fa la ruta. Si no es posen d'acord, han d'informar a través de l'app que finalment no compartiran la ruta (clickar l'opció \"declinar\" qui ofereix la ruta, o \"cancel·lar\" qui volia enviar la comanda).","Funcionalitats de l'app"),
    FaqItemModel("No es pot pagara a través de l'app", "No. És una funcionalitat que ens agradaria poder implementar en el futur però ara mateix no tenim el pressupost necessari per pagar-la. A més a més, no volem ser un intermediari i creiem en molts mecanismes de pagament, no només els euros o altres monedes; és quelcom que volem treballar bé abans d'incloure-ho.","Funcionalitats de l'app"),
    FaqItemModel("També es poden compartir seients del cotxe", "Sí. Creiem que és una bona manera per amortitzar encara més les rutes.","Funcionalitats de l'app"),
    FaqItemModel("Trobo a falta alguna funcionalitat. Què puc fer?", "Escriure a rutescompartides[arroba]riseup.net. Així ho tindrem en compte quan tinguem pressupost per aplicar millores i funcionalitats pendents. També pots escriure al correu per involucrar-te en el grup motor del projecte.","Funcionalitats de l'app"),
    FaqItemModel("L'app calcula l'espai disponible al vehicle automàticament?", "No. L'app permet que qui fa la ruta indiqui l'espai disponible aproximat en metres cúbics, però no actualitza aquesta xifra quan s'han acceptat paquets a la ruta. És una funcionalitat pendent pel futur.","Funcionalitats de l'app"),
    FaqItemModel("Puc crear una comanda sense data?", "Sí, indicant només la data mínima i marcant l'opció de \"data màxima flexible\". Així es dóna més marge a que algú que fa rutes entomi la teva comanda.","Funcionalitats de l'app"),
    FaqItemModel("Puc crear una oferta de ruta sense data?", "No. Per tal que qui busca ruta pugui triar la que li vagi millor, s'ha considerat important que calgui posar la data i l'hora prevista de la ruta quan se'n crea una.","Funcionalitats de l'app"),
    FaqItemModel("Timeouts", "L'app té diversos timeouts (temps límits) per assegurar que les coses no s'hi encallen eternament i perquè les usuàries ens responsabilitzem de les rutes/comandes que han acceptat i amb el funcionament d'aquesta app.\n" +
            "\n" +
            "Timeout per comandes amb data màxima flexible: 30 dies (si passat aquest temps la comanda no ha trobat ruta, s'autoelimina).\n" +
            "Timeout per editar o cancel·lar una RUTA amb peticions de comandes: 24 hores (perquè les comandes puguin cercar alternatives amb una mica de temps).\n" +
            "Timeout per editar/cancel·lar una COMANDA amb ruta assignada: 24 hores\n" +
            "Timeout per valorar una ruta/comanda: 96 hores (un cop passats els 4 dies, es publiquen les valoracions que hi hagi i ja no s'hi poden afegir comentaris. Abans d'aquest termini, fins que totes dues parts no s'han valorat mútuament, no es publiquen les valoracions).","Funcionalitats de l'app"),
    FaqItemModel("Les rutes són de només anada o d'anada i tornada?", "Les rutes són només d'anada. És a dir, del punt A al punt B (amb els punts intermitjos que s'hi indiquin). Però no contempla la tornada del punt B al A.","Funcionalitats de l'app"),
    FaqItemModel("I si vull fer una ruta d'anada i tornada?", "En aquest cas tens dues opcions:1. Crear dues rutes independents (una d'anada i l'altra de tornada).2. Crear una ruta punt A - punt B - punt A, amb la destinació com a punt intermig. (És a dir Lleida-Tarragona-Lleida si es va i es torna a Tarragona pel mateix lloc).","Funcionalitats de l'app"),
    FaqItemModel("Puc fer una ruta circular?", "Oi tant! Posar el mateix lloc com a punt d'origen i de destí, i llavors com a punts intermitjos tots els llocs per on saps que pararàs.","Funcionalitats de l'app"),
    FaqItemModel("Es poden portar comandes a particulars? O només botigues/restaurants/..?", "L'app no entra en el tipus de persona destinatària de les comandes. Sí que és veritat que l'entrega a particulars (B2C) sol ser més complicada, i potser hi ha usuàries de l'app que indiquen al seu perfil que només treballen amb empreses (B2B). Però també pot haver-hi el cas contrari: usuàries que es dediquin a fer entregues a domicili.","Funcionalitats de l'app"),
    FaqItemModel("I si vull fer una ruta d'anada i tornada", "En aquest cas tens dues opcions:\n" +
            "1. Crear dues rutes independents (una per l'anada i l'altra per la tornada)\n" +
            "2. Crear una ruta punt A - punt B - punt A, amb la destinació com a punt intermig. (És a dir Lleida-Tarragona-Lleida si es va i es torna a Tarragona pel mateix lloc)","Funcionalitats de l'app"),
    FaqItemModel("És legal portar paquets de tercers al teu vehicle?", "Sí, però seguint una normativa legal. Tothom qui fa servir aquesta app és responsable de seguir-la. En cap cas és responsabilitat de l'app.\n" +
            "Al web de la generalitat hi ha molta informació al respecte, amb un document d'informació general molt aclaridor per introduir-se en el tema.\n" +
            "\n" +
            "Segons afirmen des del Punt d'Informació del Departament de la Viceprèsidència i de Polítiques Digitals i Territori de la Generalitat de Catalunya, RutesCompartides.cat desenvolupa una activitat en l'àmbit de la societat de la informació adreçada a posar en contacte per mitjans telemàtics l'oferta i la demanada i per tant, no és necessària la condició d'OT (Operador de Transports).\n" +
            "Pel que fa a les empreses que realitzen materialment el transport privat complementari (transport amb productes propis), han de disposar de la corresponent autorització, si el vehicle supera la MMA de 3,5 tones. En qualsevol cas, aquest règim de transport privat complementari, no permet transportar mercaderies que no tinguin la condició de mercaderia pròpia. En cas contrari (transport de mercaderies alienes), caldrà disposar d'autorització de transport públic, sempre que el vehicle tingui una MMA superior a 2 tones.", "Altres"),
    FaqItemModel("Aquesta app assegura les mercaderies que comparteixen rutes?", "No, en cap cas.", "Altres"),
    FaqItemModel("Aquesta app es fa responsable de les rutes compartides i/o de les incidències que puguin sorgir arran del seu ús?", "No. L'app facilita que es comparteixin rutes i que les persones involucrades es posin en contacte. Però no es fa responsable del que pugui passar a partir d'aquí. Si hi ha alguna incidència (problemes d'horaris, problemes d'entregues, trencaments, etc.), s'ha de resoldre de forma externa a l'app, directament entre les persones implicades. El que sí que ofereix l'app és la funcionalitat de valorar l'altra part després de compartir la ruta, i que així quedi constància de com ha anat el procés, com a mecanisme de creació de confiança envers els seus usuaris.", "Altres"),
    FaqItemModel("Els transportistes professionals poden fer servir aquesta app?", "No: aquesta és una app per compartir rutes i no per buscar clients. Els/les transportistes que vulguin acceptar comandes per aprofitar millor les seves rutes poden fer-ho, però el preu del transport ha de ser proporcionat als costos i no cercant el lucre.", "Altres"),
).groupBy {
    it.category
}.toMap()